### ISSUE TITLE
Confused on the setup

### ISSUE THREAD

**Issue by tlplayer** [mrthinger/wow-voiceover#1]
Hi,

Great work on the addon. I loaded the game and got an unexpected symbol expected near the # on line 3 for the fuzzy search function. Am I supposed to do anything besides just drag and dropping the addon inside of the addons folder? I'm also on 1.12.1 if that might throw a wrench in the gears. Thanks.

**Comment by mrthinger** [comment]
The fuzzy search is used for matching dialog to a sound file, so I'd imagine you might be missing a lookup table.

Did you copy the addon code from the repo directly or extract it from the released ZIP? The zip has everything pre-generated for barrens and durotar.

**Comment by mrthinger** [comment]
File structure should look like this.
![image](https://user-images.githubusercontent.com/5274534/226154980-6bae09e9-38ed-4231-8dca-343e5f1d5a52.png)
![image](https://user-images.githubusercontent.com/5274534/226154982-70a4a923-b1fb-47a9-88b1-b79788210590.png)

**Comment by tlplayer** [comment]
It seems to be using the # to get the size of the array instead of table.getn. I'll test it. Could be 1.12.1 version of lua is older and doesn't have the # character for array size.

**Comment by tlplayer** [comment]
It seems it can't find the backdrop template in the SoundQueueUI:24 where is the UI parent defined?

**Comment by tlplayer** [comment]
Is there an addon dependency that defines the backdrop template the sound queue uses? what addons do you have loaded?

**Comment by mrthinger** [comment]
That actually makes sense why it might not be working. Just remove backdrop template from that line of code. It doesn't actually do anything.

That argument probably doesn't exist on a classic client. It's used for the background of the queue UI, but I thought it looked better without one and never removed the string arg.

**Comment by tlplayer** [comment]
it also can't seem to pickup on events from the 1.12.1 client odd. I removed the ui portion just to see if it would play the sound but logs an error when the event happens.

**Comment by mrthinger** [comment]
All of the event triggering is done in EventHandler.lua. Its a very short file and should be somewhat easy to abstract depending on the game client version.

**Comment by tlplayer** [comment]
Yeah I think the 1.12.1 conversion is a bit more messy than I'd like. I'm just going to wait for SOM 2 and enjoy it then (:

**Comment by tlplayer** [comment]
The way I ended up solving this issue is using the hermes proxy client with a 1.14.2 classic client then the addon worked very well. closing this issue now.
