### ISSUE TITLE
Backlog idea: Unique NPC voices

### ISSUE THREAD

**Issue by DawidMichniuk** [mrthinger/wow-voiceover#10]
Example npcs that should have a unique voice:
- Thrall
- King Bronzebeard
- Malfurion

**Comment by falconmick** [comment]
I've had an idea already that the concept of sound packs could be a useful add to the addon, basically build a plugin API that lets users download additional either small or large packs of gen voices and override the base pack. Would be a good approach as eventually we might hit a limit on the release download GBs on github so splitting the addon from the sound pack could be achieved via torrents and people could upload their own packs through torrents and the addon would simply update via curseforge (probably can't at the moment given 1gb size)

**Comment by mrthinger** [comment]
I built a site to handle this: https://allvoice.ai

At time of commenting, the site is functional but not 100% ready to be used by everyone.
