### ISSUE TITLE
Crash when talking to goblin

### ISSUE THREAD

**Issue by Zergei** [mrthinger/wow-voiceover#101]
everytime i speak to certain Goblins for example in Tanaris or Ratchet a crash happens with a roll back too and gives me this message 
![image](https://github.com/mrthinger/wow-voiceover/assets/1284407/e8315c20-7bf0-4e19-8ed5-004ceb129b69)

**Comment by TRPB** [comment]
did you ever manage to fix this? I get the exact same issue on the latest version
