### ISSUE TITLE
Same voice per NPC

### ISSUE THREAD

**Issue by bisforboman** [mrthinger/wow-voiceover#107]
Currently I guess the voice line is unique per quest, which makes it a bit wierd to have an NPC completely change voice when receiving a new quest. 

If it would be possible I guess it would be nice to have about the same voice per NPC rather than per quest.

**Comment by mrthinger** [comment]
This was a limitation of elevenlabs with low stability options selected along with my inexperience making voices. This should not be an issue in the next version. The website I'm making allows us to create a unique voice for each NPC instead of it being based on race/gender.
