### ISSUE TITLE
Create authentic troll voice

### ISSUE THREAD

**Issue by DawidMichniuk** [mrthinger/wow-voiceover#11]
Problem with exaggerated Jamaican accents

**Comment by mrthinger** [comment]
wondering if we can find a similar accent that has better data for.

**Comment by falconmick** [comment]
I would say for now it will do, there is allot of more customisation coming down the pipe for the AI tool, once there's better control that's when we should regen as it's expensive.

Idea: when the ability to adjust tone or mood arrives we use sentimental analysis to auto adjust the parameters!

**Comment by mrthinger** [comment]
Closing this as it is going to be handled as part of the v2 website https://allvoice.ai
