### ISSUE TITLE
[SUGGESTION] Dynamic volume levels while VoiceOver is playing

### ISSUE THREAD

**Issue by cantreadcode** [mrthinger/wow-voiceover#113]
Often times I can barely hear VoiceOver because the ingame music is much louder or there is a loud ambient track.

If it were possible, please add the ability to adjust the volume levels of other audio channels while VoiceOver is playing.

**Comment by mrthinger** [comment]
By default, VoiceOver plays on the master channel which means its already playing as loud as the game will possibly let it. To make the voices louder. You have to turn down the volume of the other channels and turn up WoW on your volume mixer.
