### ISSUE TITLE
Classic Era Update 1.15.0 (Season of Discovery)

### ISSUE THREAD

**Issue by maximus210793** [mrthinger/wow-voiceover#115]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game  Version of 1.15.0 (Season of Discovery)?
Would be awesome, thanks a lot in advance!

**Comment by mrthinger** [comment]
From my own use so far, the current version still works without any issues. I'll increment the interface number and update Ace3 which will make the warning go away.

**Comment by mrthinger** [comment]
Ace had no updates so I just bumped the interface number. Released in v1.4.3.
