### ISSUE TITLE
Cvar and Index Field bug

### ISSUE THREAD

**Issue by Zergei** [mrthinger/wow-voiceover#118]
so i installed the new update but got 2 bugs. 
the first one is this
"1x AI_VoiceOver-1.4.3\DataModules.lua:201: Couldn't find CVar named 'lastAddonVersion'
(tail call): ?:
(tail call): ?:
AceAddon-3.0-5:510: in function `InitializeAddon'
AceAddon-3.0-5:622: in function <...I_VoiceOver\3.3.5\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

  ---"

this first bug  has a conflict with this addon [https://gitlab.com/Tsoukie/classicapi](url)  which the creator find a workaround for it here [https://gitlab.com/Tsoukie/classicapi/-/issues/2](url) but is not a permanent solution because each new version of voice over will have this bug 

the second one is this:
"2x AI_VoiceOver-1.4.3\Options.lua:621: attempt to index field 'frame' (a nil value)
AI_VoiceOver-1.4.3\Options.lua:475: in function `func'
AI_VoiceOver-1.4.3\SoundQueueUI.lua:479: in function `OnClick'
LibDBIcon-1.0-44:179: in function <...VoiceOver\3.3.5\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:177>

Locals:
info = nil

  ---"

**Comment by mrthinger** [comment]
Which wow client version is this and could you post the other mods you're using?

**Comment by Zergei** [comment]
> Which wow client version is this and could you post the other mods you're using?

3.3.5 and i linked the other addons im using while im was describing the bugs i found
