### ISSUE TITLE
Wotlk Error #132 

### ISSUE THREAD

**Issue by Zergei** [mrthinger/wow-voiceover#119]
this crash happens only in these situations:

deliver a quest to a goblin or take quest from a goblin
when i take quest from a goblin and then talk to another NPC

im using last version of Voice over and the Vanilla Sounds for WOTLK 3.3.5

![wow_error](https://github.com/mrthinger/wow-voiceover/assets/1284407/9daeeaa1-57b8-414a-9651-c04a1af54da8)

**Comment by helsif** [comment]
I had the same issue. The crash was happening on specific goblins, when using the addon together with HD character models.  Works, when hiding NPC portraits.
