### ISSUE TITLE
Add Missing Voices in currently covered zones

### ISSUE THREAD

**Issue by DawidMichniuk** [mrthinger/wow-voiceover#12]
Current known cases:

- Satyr in Night elf starting zone
- The Woodland Protector dryad Tarindrella in night elf's starting zone
- Earth elemental for shaman quest
- Human kids:
  - Package for Thurman - https://www.wowhead.com/classic/quest=334/package-for-thurman
  - Goldtooth - https://www.wowhead.com/classic/quest=87/goldtooth
  - Pie for Billy - https://www.wowhead.com/classic/quest=86/pie-for-billy

**Comment by lightmor** [comment]
The Woodland Protector continuation quest in elfs starting zone

**Comment by falconmick** [comment]
Nelf satyr's name is Tarindrella and one of her quests is called The Woodland Protector

**Comment by HelveteTV** [comment]
Kids doesn't seem to have any voiceover right now, example quests:

Package for Thurman - https://www.wowhead.com/classic/quest=334/package-for-thurman
Goldtooth - https://www.wowhead.com/classic/quest=87/goldtooth
Pie for Billy - https://www.wowhead.com/classic/quest=86/pie-for-billy

**Comment by DawidMichniuk** [comment]
Good shout, thank you for highlighting this and for including example quests!

That being said, I can confirm the altar boy for missing diplomat questline does indeed have a voice and that's just generic human male sound. It's pretty traumatic to hear a kid with such a deep voice so we might need to make a unique voice for all kids.

@mrthinger - long term, we probably need to change the data for all the kid npcs to a seperate race to ensure we don't re-do it with grown human voices as we iterate over all the voice lines down the line.

**Comment by bjg123456** [comment]
I also receive "sound does not exist for" error messages and no audio for the following:
-Mountaineer Kadrell [https://www.wowhead.com/classic/npc=1340/mountaineer-kadrell](url)
-Report to Mountaineer Rockgar [https://www.wowhead.com/classic/quest=468/report-to-mountaineer-rockgar](url)
-Powder to Ironband [https://www.wowhead.com/classic/quest=302/powder-to-ironband](url)
-Resupplying the Excavation [https://www.wowhead.com/classic/quest=273/resupplying-the-excavation](url)

**Comment by mrthinger** [comment]
Closing as its going to be addressed by V2 effort. The main issue was unique models had no voice if anyone sees this in the future.
