### ISSUE TITLE
Getting error message when starting

### ISSUE THREAD

**Issue by GentlemanHawk** [mrthinger/wow-voiceover#120]
I get this error message when i start and dont know what to do about it.

sorry to bug you
![Screenshot 2023-12-30 103611](https://github.com/mrthinger/wow-voiceover/assets/155247548/8c1bd9aa-7754-44e1-959f-b659a9e3e06f)

**Comment by mrthinger** [comment]
What version is the addon, what version is the game, what other addons are you using?

**Comment by GentlemanHawk** [comment]
I'm playing Solocraft which uses 1.12.1. I downloaded the one for 1.12 but when I open the file it has other versions in folders as well. The only other addon is a party control panel that lets you summon and command party bots.

**Comment by GentlemanHawk** [comment]
I'm sorry. I redownloaded it and it is working now. Thank you for the response.
