### ISSUE TITLE
static vmangos release url

### ISSUE THREAD

**Issue by DawidMichniuk** [mrthinger/wow-voiceover#3]
Hi, in tts_cli/init_db.py, your VMANGOS_DB_DUMP_URL points to a fixed file name - this is now broken as Vmangos just updated.

Instead of doing that, try using "https://api.github.com/repos/vmangos/core/zipball/db_latest" - this should point to the latest release every time and proc a zip download!

I'd make this change myself and create a pull request but seems you disabled branching the repo?

**Comment by mrthinger** [comment]
Are you unable to fork the repo?

**Comment by DawidMichniuk** [comment]
My bad, I'm too used to working with branches - made a PR now!

**Comment by mrthinger** [comment]
Your pr doesnt pull the most recent db dump. I think it pulls the source. I've manually update the static URL for now, but we need to find a long term solution for pulling the db dump.

**Comment by DawidMichniuk** [comment]
Found a fix now that gets the latest version and then downloads the correct DB dump zip!

**Comment by mrthinger** [comment]
Awesome, thanks! I merged in it. I think we should follow up by checking the name of the file to see if it contains db in it, just in case there is more than 1 download in the future at that link.
