### ISSUE TITLE
UI doesn't work

### ISSUE THREAD

**Issue by simsekb** [mrthinger/wow-voiceover#32]
When I have the addon activated, I can't press any menu items. I think the addon is conflicting with my Dominos actionbars.

Current addon version: 1.0.1
Dominos version: 10.0.22

**Comment by mrthinger** [comment]
Try updating the addon on curse, it removes the invisible frame from this addon. Let me know if that fixed the issue.

**Comment by simsekb** [comment]
Yup, that fixed it, nice!
