### ISSUE TITLE
Voice of non-questgivers are also played

### ISSUE THREAD

**Issue by simsekb** [mrthinger/wow-voiceover#34]
When I fly and speak with an npc or with an innkeeper, I get to hear its dialogue. Problem persists while the setting is put on "only quest-givers" in the settings.

Unsure what version I'm using currently.

**Comment by mrthinger** [comment]
What is the expected behavior? If its that innkeepers shouldnt play dialog more than once, try the Once Per NPC option.

**Comment by simsekb** [comment]
The expected behavior is when obtaining a quest that it gets read. The dialogues with innkeepers or similar don't add any value to my experience per se. But the ticket is more because I thought it didn't work as it should.

**Comment by mrthinger** [comment]
If you turn the gossip playback option to Always, does that fix the issue?

Do you have any suggestions to make the wording clearer if so?
