### ISSUE TITLE
Is it possible to backport this to 1.12 or is impossible

### ISSUE THREAD

**Issue by Bittermens** [mrthinger/wow-voiceover#38]
just asking

**Comment by Shonatan** [comment]
Wondering this myself. There's some word online about using HermesProxy in order to port to other clients.

**Comment by mrthinger** [comment]
its possible with a reduced feature set.

**Comment by nazriel** [comment]
@mrthinger are you aware if anyone is working on 1.12 port?
I was thinking about chiming in and trying to bring this to Turtle - but I don't want to duplicate someones work if it is already in progress

**Comment by mrthinger** [comment]
> @mrthinger are you aware if anyone is working on 1.12 port? I was thinking about chiming in and trying to bring this to Turtle - but I don't want to duplicate someones work if it is already in progress

I've started it and have backfilled in the core missing functionality from the 1.12 client. Ill push my wip branch soon.

**Comment by mrthinger** [comment]
@nazriel #50 WIP
