### ISSUE TITLE
Is it possible to add multilanguage support?

### ISSUE THREAD

**Issue by Astraorion** [mrthinger/wow-voiceover#43]

**Comment by mrthinger** [comment]
Not at the moment. The main limitations are technology and cost. Elevenlabs will eventually add other languages but we'd need twice the amout of funds to generate even 1 more language.

**Comment by Astraorion** [comment]
Here in Germany wow is insanely popular, I am sure you would make many people happy

**Comment by GierlJn** [comment]
> Not at the moment. The main limitations are technology and cost. Elevenlabs will eventually add other languages but we'd need twice the amout of funds to generate even 1 more language.

Elevenlabs now support a lot of languages. I see there a lot of people that desperately want multilanguage support. Can you give an estimate of the size of funds that are required for this? I think there are enough people to pay for it.

**Comment by mrthinger** [comment]
> > Not at the moment. The main limitations are technology and cost. Elevenlabs will eventually add other languages but we'd need twice the amout of funds to generate even 1 more language.
> 
> Elevenlabs now support a lot of languages. I see there a lot of people that desperately want multilanguage support. Can you give an estimate of the size of funds that are required for this? I think there are enough people to pay for it.


Youre correct. The main issue is having a complete text database in other languages. I might be wrong, but as I recall there are quite a few holes for other languages.

I'm building a site that could technically support crowdsourcing voicemodels for other languages so I'm less worried about that.


If someone could take a look at the scraping plan I have in retail-plan.md, that should be enough to slowly pool everything we'd need to ever generate for every version of the game. I don't personally have plans to do that at this time. I want to get the crowdsource website done and generate vanilla, tbc, and wrath with new voices from the site.

**Comment by mrthinger** [comment]
This is being worked on. Consolidating discussion of this to: https://discord.gg/KAUhSseXS7
