### ISSUE TITLE
Please make it also for TBC and Wrath

### ISSUE THREAD

**Issue by Astraorion** [mrthinger/wow-voiceover#47]
Could you please make this masterpeace of awesomeness also for TBC and Wrath classic?

**Comment by mrthinger** [comment]
I'm copying my answer from the FAQ in the discord. Ideally we'll have a website in the future as a central point to explain the current project's direction.


### Is X version of the game currently supported?
Sound has currently only been generated for Vanilla, meaning non-vanilla zones will not have sound even if the addon supports that version of the game.
Supported: 1.14 (Blizz Vanilla), 3.4 (Blizz Wrath)
Unsupported: 1.12 (Private Vanilla), 3.3 (Private Wrath), 10.0 (Blizz Retail)

### Can you add support for Wrath/TBC?
We use Elevenlabs for text-to-speech, which charges on a per-text-character basis. Generating sound for new expansions is prohibitively expensive for me to fund alone (I fronted the first $500 for Vanilla before releasing). Our next step is adding sounds for TBC and Wrath and porting the addon to work on the currently unsupported game versions. A goal has been set up on my Ko-fi; if we reach that, I will be able to add those features. https://ko-fi.com/evanpierce/goal?g=8

The funds cover:
- Elevenlabs TTS
- Development of new voices
- Improvement to existing voices
- Ports for 1.12 (Private Vanilla), 3.3 (Private Wrath), 10.0 (Blizz Retail)

**Comment by RichardB0101** [comment]
Hey man, I suggest setting up a [donation counter](https://imgur.com/a/STBX2Xk), but for streams. I mean we might ask some of the private server streamers to ask their community to raise funds. Because there are still plenty of people who would love to donate but are not aware of this addon, so the only bottleneck is a little bit of marketing. Would like to contribute as much as possible, because I'm so hyped up on this, can't wait myself till it comes out for wow private servers!

**Comment by mrthinger** [comment]
> Hey man, I suggest setting up a [donation counter](https://imgur.com/a/STBX2Xk), but for streams. I mean we might ask some of the private server streamers to ask their community to raise funds. Because there are still plenty of people who would love to donate but are not aware of this addon, so the only bottleneck is a little bit of marketing. Would like to contribute as much as possible, because I'm so hyped up on this, can't wait myself till it comes out for wow private servers!

Good idea. I have noted this suggestion. I'm closing this ticket because progress and discussion about this is taking place in the [discord](https://discord.gg/CmTh3HjJjP).
