### ISSUE TITLE
Is it possible to automatically end the voice dialogue when disengaging with the NPC, and permanently hide the window?

### ISSUE THREAD

**Issue by apav** [mrthinger/wow-voiceover#48]
Hi, thank you for this wonderful addon! 

I was wondering if it was possible to make an option to automatically cancel the voice dialogue when you stop talking to the NPC when the dialogue/quest window goes away when you walk away, close out of the window, or accept the quest? 

Also, is it possible to make an option to permanently hide the addon UI window until you toggle it again, either by a command or minimap button? Because even when auto-hide is enabled, it still pops up when a voice is playing. 

Thank you so much!

**Comment by mrthinger** [comment]
permanently hiding the window has been implemented.
