### ISSUE TITLE
Dialog channel not working.

### ISSUE THREAD

**Issue by lightmor** [mrthinger/wow-voiceover#65]
Setting `Sound Channel` to `Dialog` lead to strange behaviour. After interaction with quest giver the dialog channel get muted in sound setting of the game and there is no sound of the addon. Other channels work fine.

P.S. In early versions of the addon this channel worked fine.

**Comment by coRpTitan** [comment]
I have same issue - version 1.3.1

**Comment by mrthinger** [comment]
This is a UX/UI issue. Turning off Auto-mute npcs should fix the issue (it works by muting the dialog when VoiceOver is playing).

I think the fix to this would be to have a warning when Dialog channel is selected and auto-mute are on at the same time.

**Comment by inertzest** [comment]
WoW Sound Effects must be enabled for Sound Channel: Dialog to work (otherwise "Your sound is turned off" debug message). You can still effectively mute sound effects if you find them annoying by adjusting them to 0% volume.
