### ISSUE TITLE
Will you release that also with German language ?

### ISSUE THREAD

**Issue by delaware1999** [mrthinger/wow-voiceover#68]
Will you release that also with German language ?

**Comment by mrthinger** [comment]
**Can you add X language?**
Each new language requires us to generate a copy of all of the current files, which is prohibitively expensive (we still dont 1 copy of everything in English). We'd also need new voice models for each language. Elevenlabs TTS currently only supports English but is planning other language support in the future.

Based on that, the answer is probably not anytime soon. I'm planning on reaching out to Elevenlabs to see if we can get some special pricing so there is some potential in the future.
