### ISSUE TITLE
can't Extract the files  AI_VoiceOverData_Vanilla-v1.0.0.

### ISSUE THREAD

**Issue by Drwarlocke** [mrthinger/wow-voiceover#69]
Download no problem open it no problem Extractging yea right it dont work at all.. Have delete liked 5 time download 5 times and 0 work please fix it

**Comment by mrthinger** [comment]
Curse stops the download after a certain amount of time. Try downloading from https://github.com/mrthinger/wow-voiceover/releases/latest
