### ISSUE TITLE
Please do it in another langages

### ISSUE THREAD

**Issue by Kerweek** [mrthinger/wow-voiceover#73]
A lot of people still don't know to read properly in 2023, and this addon can help them. I can help to do the voice in FR if you need.

**Comment by mrthinger** [comment]
Are you familiar with elevenlabs?

**Comment by Kerweek** [comment]
I discovered this with your project. But I imagine that you have your voices (like the orcs etc). Should we talk about it in private ? like Discord or something?

**Comment by Mysticalfx74** [comment]
Just want to add that this will be really useful for people with dysgraphia as my son, it will help him to take some pleasure on this game and avoid big energy loss ! I agree with Kerweek as we are on another language, If needed i can help you with French and/or Italian. Thanks again for this great job.

**Comment by elbekri** [comment]
@mrthinger i found the fr npc voice at wowhead and i have an account in 11lab i added fr orc-male voice to my account, i can generate the audio but the text from mango db is still in english

I'm trying to follow the lead through your code to make it on my own but i'm sure it will take like 5mn for you to add the language_id in your sql script ^^ (the fr is fe/male_text_loc3 in locales_broadcast_text if you wonder)

**Comment by elbekri** [comment]
Ps: i don't have a lot of free time but i'll be happy to help with other language as well (And also to help for the retail version if you want)

**Comment by mrthinger** [comment]
> @mrthinger i found the fr npc voice at wowhead and i have an account in 11lab i added fr orc-male voice to my account, i can generate the audio but the text from mango db is still in english
> 
> I'm trying to follow the lead through your code to make it on my own but i'm sure it will take like 5mn for you to add the language_id in your sql script ^^ (the fr is fe/male_text_loc3 in locales_broadcast_text if you wonder)
> 
> EDIT: Sooo even if the text is good the accent is not. For everyone who is wondering why this is only in english : I spent an entire day trying to make it but i found there is no satisfying alternatives to eleven labs and eleven labs is exclusively working with english voices at the moment
> 
> Seems like the only way to make it happen is to developp an equivalent of eleven labs for fr voices or to wait for someone else to do it, maybe one day elevenlabs themself would make it happen

Elevenlabs is working on a multi-lingual model.

**Comment by RobinFrcd** [comment]
The Multilingual model has been released on April 26th !

**Comment by Newfriendfromwinter** [comment]
Any progress on this?  I'm looking to learn French, and I thought it'd be a great excuse to play some WoW.

**Comment by jbusodev** [comment]
I have got familiar with ElevenLabs and trained a few voices in frFR already. I'm curious to know if you have a process to quickly export quest texts and create the mp3 files with scripts (with the help of WoW API & ElevenLabs API) ?

@mrthinger Since you have already stored all NPCs IDs in the english version, do you have an idea of the folder structure to support other languages? Maybe we could work on a Settings UI to allow players to pick between languages?
