### ISSUE TITLE
remove overlaping sounds.

### ISSUE THREAD

**Issue by tra8cer** [mrthinger/wow-voiceover#87]
Is there a way to remove the standard quest sounds and voices so that the sounds do not overlap?

**Comment by tra8cer** [comment]
i may have found some option, but not the chime noise.

**Comment by tra8cer** [comment]
music as well

**Comment by jbusodev** [comment]
Please provide the steps you took so others who are interested can reproduce your solution

**Comment by mrthinger** [comment]
Unless we get information this issue is non-actionable. There are already a lot of work put into options for handling sound overlap. The main thing is the mechanism is different in every version of the game.
