### ISSUE TITLE
How can we help develop the addon?

### ISSUE THREAD

**Issue by f0vy** [mrthinger/wow-voiceover#90]
How can the community help develop the addon?

My question is - are you interested in expanding the number of voiced-over NPCs and how can I help you?
Could you please provide an example of sql or some other type of data that would be useful for you to input and implement in future versions of the addon?

Also, if you need a second opinion on something in russian, would be honored to help.

**Comment by mrthinger** [comment]
Yes. I actually uploaded a plan yesterday for the community. I have someone started on Part 2 (scraping wow text). I'm working on Part 1. If youre looking to join the effort for Part 2 join the discord and @mrthinger. I can connect you with the other dev working on this and help answer clarifying questions.

That goes for anyone else that'd like to help too.

https://github.com/mrthinger/wow-voiceover/blob/master/RETAIL-PLAN.md

The plan is marked as retail, but includes everything we'd need for any expansion or language.
