### ISSUE TITLE
Wrong avatar when replaying quest from quest log

### ISSUE THREAD

**Issue by harrypotterIUP** [mrthinger/wow-voiceover#93]
I'm on WoW 1.12.1 and when I replay a quest from the quest log, the audio plays, the pop-up window shows up and it also displays the correct NPC name - but the displayed avatar is simply a book instead of the speaking NPC.

The correct avatar did show up when picking up the quest from the NPC. It's only an issue when replaying from the quest log.

:heart: Thanks!

**Comment by mrthinger** [comment]
its a limitation of the 1.12 client.
