### ISSUE TITLE
wotlk quest text and npcs

### ISSUE THREAD

**Issue by Cptmaxon** [mrthinger/wow-voiceover#95]
Hey guys,
I saw you downloaded the npc text and name from something called https://github.com/vmangos, which only has the vanilla data.
do you guys also have a source for these strings for TBC and WOTLK?
thanks

**Comment by MyTechnoHunter** [comment]
> Hey guys, I saw you downloaded the npc text and name from something called https://github.com/vmangos, which only has the vanilla data. do you guys also have a source for these strings for TBC and WOTLK? thanks

try https://github.com/cmangos

**Comment by mrthinger** [comment]
https://github.com/cmangos/mangos-wotlk

I'm working on a website now to crowdsource the required voices for wrath and tbc. The details are outlined in Retail-Plan.md

We hit the goal to generate that text.

**Comment by mrthinger** [comment]
I'm closing this because its included as part of the v2 effort and its ultimately not going to get tracked in this issue.
