### ISSUE TITLE
Out of date/quests missing

### ISSUE THREAD

**Issue by Zolef1** [mrthinger/wow-voiceover#98]
Hi!

Thank you for making this addon. I would like to submit a bug/issue/ask for help.

I downloaded the latest 2 files from the page https://github.com/mrthinger/wow-voiceover/releases and one of the addons in the addon list in the character screen is red and marked as out of date. I hit the "load out of date" addons box and the addon technically works.

However, some quests that are 100% vanilla normal quests don't allow the quest to be read with the voice over and im not able to press the play button in the quest log either. 

Specifically the quests "The captains chest" and "Akiris by the Bundle" "The bloodsail buccaneers" and some other normal vanilla quests.

**Comment by altsor** [comment]
I have the same issue!

**Comment by mrthinger** [comment]
this seems like it could be a lot of different things. Some vanilla quests are still not voiced, sometimes the client needs a restart to load the addon properly because the sound pack will always be out of date and the force loading logic in the player doesn't work in some specific cases.
