### ISSUE TITLE
QuestLog PlayButtons covers the number counters to indicate who in your party also has the quest 

### ISSUE THREAD

**Issue by Dyaxler** [mrthinger/wow-voiceover#99]
...makes it difficult to know which quests to share with other members in your party. I suggest moving the PlayButtons further left.

https://github.com/mrthinger/wow-voiceover/blob/30511bcdb28e7a20554ab72d29fe88e87d4115b3/AI_VoiceOver/QuestOverlayUI.lua#L42

`playButton:SetPoint("LEFT", normalText, "LEFT", -16, 0)`

**Comment by Dyaxler** [comment]
BTW... one of our supporters reported this. He wasn't using any QL addon in Wrath Classic. Some of his characters bugged and some don't apparently. Might be a race condition where the Playbuttons are getting set before the QL text updates for party member quest counts?

**Comment by Dyaxler** [comment]
False alarm

**Comment by mrthinger** [comment]
What ended up being the issue? Old addon version?

**Comment by Dyaxler** [comment]
They said they had their QL open shortly after login and right after joining a group. Once they closed their QL and reopened it... it refreshed and moved the PlayButtons over. They assumed PlayButtons didn't update its position after joining a group is my guess.
